version: "3"
services:
  server:
    build: ./server
    env_file:
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./server:/home/node/code
      - /server/home/node/code/node_modules
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: pass
