version: "3"
services:
  # Client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    stdin_open: true
  # Server
  server:
    build: ./server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "5001:5555" # for prisma studio
    volumes:
      - ./server:/app
      - "/app/node_modules"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: pass
